config/routes.rb
Rails.application.routes.draw do
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  scope '(:locale)' do
    resources :users
    resources :plannedtransactions do
      member do
        patch 'close_and_clone'
      end
      collection { post :buchungen_anzeigen }
    end
    resources :unique_planned_transactions
    resources :categories
    resources :transactions do
      collection { post :import }
      collection { delete :delete_all }
    end

    get '/gegenbuchung/', to: 'unique_planned_transactions#gegenbuchung', as: 'unique_planned_transactions_gegenbuchung'
    get '/transactions/:year/:month', to: 'transactions#show_by_year_month', as: 'transactions_show_by_year_month'

    get '/yearlybudget/:year/:month', to: 'budget_by_year#show_by_year', as: 'show_by_year', defaults: { percentage_or_absolute: 'percentage' }
    get '/yearlybudget', to: 'budget_by_year#index', as: 'budget_by_year_index'
    get '/yearlybudget_by_category/:year/:month/:category_id', to: 'budget_by_year#show_by_year_category', as: 'show_by_year_category', defaults: { percentage_or_absolute: 'percentage' }

    get '/budget/:year/:month', to: 'budget#show_by_year_month', as: 'show_by_year_month', defaults: { percentage_or_absolute: 'percentage' }
    get '/budget/:year/:month/percentage_or_absolute', to: 'budget#show_by_year_month', as: 'show_by_year_month_absolute', defaults: { percentage_or_absolute: 'absolute' }

    get '/budget_by_category/:year/:month/:category_id', to: 'budget#show_by_year_month_category', as: 'show_by_year_month_category'

    post '/buchungen_anzeigen', to: 'plannedtransactions#buchungen_anzeigen'
    
    root 'budget#index', as: 'budget_index'
  end
end

app/controllers/plannedtransactions_controller.rb
# frozen_string_literal: true

class PlannedtransactionsController < ApplicationController
  before_action :set_plannedtransaction, only: %i[show edit update destroy close_and_clone]

  # GET /plannedtransactions
  # GET /plannedtransactions.json
  def index
    @year = Date.today.year.to_s
    @month = Date.today.month.to_s
    @plannedtransactions = []
    @first_day_of_the_month = Date.new(Integer(@year), Integer(@month), 0o1)
    @plannedtransactions_all = Plannedtransaction.where(user_id: session[:user_id]).order(:category_id)
    @plannedtransactions_all.each do |plannedtransaction|
      @plannedtransactions.push plannedtransaction if plannedtransaction.occurs_in_month?(@first_day_of_the_month)
    end
  end

  # GET /plannedtransactions/1
  # GET /plannedtransactions/1.json
  def show; end

  # GET /plannedtransactions/new
  def new
    @plannedtransaction = Plannedtransaction.new
  end

  # GET /plannedtransactions/1/edit
  def edit; end

  # POST /plannedtransactions
  # POST /plannedtransactions.json
  def create
    @plannedtransaction = Plannedtransaction.new(plannedtransaction_params)
    @plannedtransaction.user_id = session[:user_id]

    respond_to do |format|
      if @plannedtransaction.save
        format.html { redirect_to @plannedtransaction, notice: 'Planned Transaction was successfully created.' }
        format.json { redirect_to plannedtransactions_url, status: :created, location: @plannedtransaction }
      else
        format.html { render :new }
        format.json { render json: @plannedtransaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plannedtransactions/1
  # PATCH/PUT /plannedtransactions/1.json
  def update
    respond_to do |format|
      if @plannedtransaction.update(plannedtransaction_params)
        format.html { redirect_to @plannedtransaction, notice: 'Planned Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @plannedtransaction }
      else
        format.html { render :edit }
        format.json { render json: @plannedtransaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plannedtransactions/1
  # DELETE /plannedtransactions/1.json
  def destroy
    @plannedtransaction.destroy
    respond_to do |format|
      format.html { redirect_to plannedtransactions_url, notice: 'Planned Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # PATCH/PUT /plannedtransactions/1
  # PATCH/PUT /plannedtransactions/1.json
  def close_and_clone
    @plannedtransaction.valid_until = Date.current.at_end_of_month
    if @plannedtransaction.save
      @plannedtransaction = @plannedtransaction.dup
      @plannedtransaction.valid_until = nil
      @plannedtransaction.valid_from = Date.current.next_month.at_beginning_of_month
      render :edit
    else
      render :show
    end
  end

  def buchungen_anzeigen
    logger.debug("test_params #{params[:buchungen_anzeigen]}")
    @year = Date.today.year.to_s
    @month = Date.today.month.to_s
    @plannedtransactions = []
    @first_day_of_the_month = Date.new(Integer(@year), Integer(@month), 0o1)
    @plannedtransactions_all = Plannedtransaction.where(user_id: session[:user_id])
    @plannedtransactions_all.each do |plannedtransaction|
      @plannedtransactions.push plannedtransaction if plannedtransaction.occurs_in_month?(@first_day_of_the_month) or params[:buchungen_anzeigen] == "on" 
    end

    respond_to do |format|
      format.js
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_plannedtransaction
    @plannedtransaction = Plannedtransaction.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def plannedtransaction_params
    params.require(:plannedtransaction).permit(:description_actiontext, :description, :amount, :purpose, :category_id, :january, :february, :march, :april, :may, :june, :july, :august, :september, :october, :november, :december, :valid_from, :valid_until)
  end
end

app/views/plannedtransactions/_form.html.erb
<%= form_with(model: plannedtransaction, local: true) do |f| %>
  <% if plannedtransaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plannedtransaction.errors.count, "error") %> prohibited this plannedtransaction from being saved:</h2>

      <ul>
      <% plannedtransaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :purpose %>
    <%= f.text_field :purpose %>
  </div>

  <div class="field">
    <%= f.label :amount %>
    <%= f.text_field :amount %><%= currency_symbol %>
  </div>
<div class="field">
    <%= f.label :description %>
    <%= f.rich_text_area :description %>
  </div>

   <section class="ex1" id="basic_usage">
  <div class="field">
	  <table>
		  <thead>
    		  <tr>
    			  <th><%= t('select_all') %></th>
				  <th><%= f.label :january %></th>
				  <th><%= f.label :february %></th>
				  <th><%= f.label :march %></th>
				  <th><%= f.label :april %></th>
				  <th><%= f.label :may %></th>
				  <th><%= f.label :june %></th>
				  <th><%= f.label :july %></th>
				  <th><%= f.label :august %></th>
				  <th><%= f.label :september %></th>
				  <th><%= f.label :october %></th>
				  <th><%= f.label :november %></th>
				  <th><%= f.label :december %></th>
			  </tr>
		  </thead>
		  <tbody>
    		  <td><input type="checkbox" id="simpleCheckAll" >All Items</input></td>
			  <td><%= f.check_box :january, class: :selectable %></td>
    		<td><%= f.check_box :february, class: :selectable %></td>
			  <td><%= f.check_box :march, class: :selectable %></td>
			  <td><%= f.check_box :april, class: :selectable %></td>
			  <td><%= f.check_box :may, class: :selectable %></td>
			  <td><%= f.check_box :june, class: :selectable %></td>
			  <td><%= f.check_box :july, class: :selectable %></td>
			  <td><%= f.check_box :august, class: :selectable %></td>
			  <td><%= f.check_box :september, class: :selectable %></td>
			  <td><%= f.check_box :october, class: :selectable %></td>
			  <td><%= f.check_box :november, class: :selectable %></td>
			  <td><%= f.check_box :december, class: :selectable %></td>
		  </tbody>
	  </table>
  </div>
   </section>

  <div class="field">
    <%= f.label :category %>
     <%= f.select :category_id, Category.where(user_id: session[:user_id]).collect {|p| [ p.name, p.id ] } %>
  </div>
  <div class="field">
    <%= f.label :valid_from %>
    <%= f.date_select :valid_from , id: :plannedtransaction_valid_from, discard_day: true%>
  </div>
  <div class="field">
    <%= f.label :valid_until %>
    <%= f.date_select :valid_until , id: :plannedtransaction_valid_until, discard_day: true, include_blank: true%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
    <script type="text/javascript">
      $(".ex1").find("#simpleCheckAll").select_all();
    </script>

app/views/plannedtransactions/_list_of_products.html.erb
    <% @plannedtransactions.each do |plannedtransaction| %>
      <tr>
        <td><%= plannedtransaction.purpose %></td>
		<td><%= Category.find(plannedtransaction.category.id).name %></td>
    <td><%= number_to_currency(plannedtransaction.amount) %></td>
		<td><%= l plannedtransaction.valid_from, format: :month_year unless plannedtransaction.valid_from.nil?%></td>
		<td><%= l plannedtransaction.valid_until, format: :month_year unless plannedtransaction.valid_until.nil?%></td>
    <td><%= check_box(plannedtransaction.january, plannedtransaction.january,  {checked:plannedtransaction.january, disabled: true}) %></td>
		<td><%= check_box(plannedtransaction.february, plannedtransaction.february,  {checked:plannedtransaction.february, disabled: true}) %></td>
		<td><%= check_box(plannedtransaction.march, plannedtransaction.march,  {checked:plannedtransaction.march, disabled: true}) %></td>
		<td><%= check_box(plannedtransaction.april, plannedtransaction.april,  {checked:plannedtransaction.april, disabled: true}) %></td>
		<td><%= check_box(plannedtransaction.may, plannedtransaction.may,  {checked:plannedtransaction.may, disabled: true}) %></td>
		<td><%= check_box(plannedtransaction.june, plannedtransaction.june,  {checked:plannedtransaction.june, disabled: true}) %></td>
		<td><%= check_box(plannedtransaction.july, plannedtransaction.july,  {checked:plannedtransaction.july, disabled: true}) %></td>
		<td><%= check_box(plannedtransaction.august, plannedtransaction.august,  {checked:plannedtransaction.august, disabled: true}) %></td>
		<td><%= check_box(plannedtransaction.september, plannedtransaction.september,  {checked:plannedtransaction.september, disabled: true}) %></td>
		<td><%= check_box(plannedtransaction.october, plannedtransaction.october,  {checked:plannedtransaction.october, disabled: true}) %></td>
		<td><%= check_box(plannedtransaction.november, plannedtransaction.november,  {checked:plannedtransaction.november, disabled: true}) %></td>
		<td><%= check_box(plannedtransaction.december, plannedtransaction.december,  {checked:plannedtransaction.december, disabled: true}) %></td>
		<td><%= plannedtransaction.description %></td>
        <td><%= link_to 'Edit', edit_plannedtransaction_path(plannedtransaction) %></td>
        <td><%= link_to 'Destroy', plannedtransaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

app/views/plannedtransactions/_plannedtransaction.html.erb
<td>
<i class='fas fa-redo'></i> <%= link_to plannedtransaction.purpose, get_path_for_plannedtransaction(plannedtransaction) %>
</td>

app/views/plannedtransactions/buchungen_anzeigen.js.erb
product = document.getElementById("products")
//alert(product.innerHTML);
product.innerHTML = "<%= j render "list_of_products" %>"
//product.innerHTML = "test"

app/views/plannedtransactions/edit.html.erb
<h1><%= t('edit_recurring_transaction') %></h1>

<%= render 'form', plannedtransaction: @plannedtransaction %>

<%= link_to 'Show', @plannedtransaction %> |
<%= link_to 'Back', plannedtransactions_path %>

app/views/plannedtransactions/index.html.erb
<p id="notice"><%= notice %></p>
<h1><%= t('recurring_transactions') %></h1>
<input type="checkbox" data-remote="true"
    data-url="buchungen_anzeigen" data-method="post" name="buchungen_anzeigen">Alte Buchungen anzeigen
<!--%= link_to '(-)', buchungen_ausblenden_plannedtransactions_path ,method: :post, remote: true %-->
<p><%= link_to t('new_transaction'), new_plannedtransaction_path %></p>
<table>
  <thead>
    <tr>
    <th><%= t('purpose') %></th>
	  <th><%= t('category') %></th>
    <th><%= t('amount') %></th>
		<th><%= t('valid_from') %></th>
		<th><%= t('valid_until') %></th>
    <th><%= (t :abbr_month_names, :scope => :date)[1] %></th>
	  <th><%= (t :abbr_month_names, :scope => :date)[2] %></th>
	  <th><%= (t :abbr_month_names, :scope => :date)[3] %></th>
	  <th><%= (t :abbr_month_names, :scope => :date)[4] %></th>
	  <th><%= (t :abbr_month_names, :scope => :date)[5] %></th>
	  <th><%= (t :abbr_month_names, :scope => :date)[6] %></th>
	  <th><%= (t :abbr_month_names, :scope => :date)[7] %></th>
	  <th><%= (t :abbr_month_names, :scope => :date)[8] %></th>
	  <th><%= (t :abbr_month_names, :scope => :date)[9] %></th>
	  <th><%= (t :abbr_month_names, :scope => :date)[10] %></th>
	  <th><%= (t :abbr_month_names, :scope => :date)[11] %></th>
	  <th><%= (t :abbr_month_names, :scope => :date)[12] %></th>
	  <th><%= t('description') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody id="products">
  <%= render "list_of_products"%>
  </tbody>
</table>

app/views/plannedtransactions/new.html.erb
<h1>New Planned Transaction</h1>

<%= render 'form', plannedtransaction: @plannedtransaction %>

<%= link_to 'Back', plannedtransactions_path %>

app/views/plannedtransactions/show.html.erb
<p id="notice"><%= notice %></p>
<% if @plannedtransaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plannedtransaction.errors.count, "error") %> prohibited this plannedtransaction from being saved:</h2>

      <ul>
      <% @plannedtransaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<p>
  <strong><%= t('description') %>:</strong>
  <%= @plannedtransaction.description %>
  <br>
  <strong><%= t('amount') %>:</strong>
  <%= number_to_currency(@plannedtransaction.amount) %>
  <br>
  <strong><%= t('purpose') %>:</strong>
  <%= text_area_tag(@plannedtransaction.purpose, @plannedtransaction.purpose, rows: 5, cols: 50, disabled: true) %>
  <br>
  <strong><%= t('category') %>:</strong>
  <%= Category.find(@plannedtransaction.category_id).name %>
  <br>
  <strong><%= t('valid_from') %>:</strong>
  <%= l @plannedtransaction.valid_from, format: :month_year %>
  <br>
  <strong><%= t('valid_until') %>:</strong>
  <%= l @plannedtransaction.valid_until, format: :month_year unless @plannedtransaction.valid_until.nil?%>
  <br>
  <table>
    <thead>
      <tr>
		  <% (1..12).each do |month| %>
        	<th><%= (I18n.t :abbr_month_names, :scope => :date)[month] %></th>
  	  	  <% end %>
      </tr>
    </thead>

    <tbody>
        <tr>
          <td><%= check_box(@plannedtransaction.january, @plannedtransaction.january,  {checked:@plannedtransaction.january, disabled: true}) %></td>
  		<td><%= check_box(@plannedtransaction.february, @plannedtransaction.february,  {checked:@plannedtransaction.february, disabled: true}) %></td>
  		<td><%= check_box(@plannedtransaction.march, @plannedtransaction.march,  {checked:@plannedtransaction.march, disabled: true}) %></td>
  		<td><%= check_box(@plannedtransaction.april, @plannedtransaction.april,  {checked:@plannedtransaction.april, disabled: true}) %></td>
  		<td><%= check_box(@plannedtransaction.may, @plannedtransaction.may,  {checked:@plannedtransaction.may, disabled: true}) %></td>
  		<td><%= check_box(@plannedtransaction.june, @plannedtransaction.june,  {checked:@plannedtransaction.june, disabled: true}) %></td>
  		<td><%= check_box(@plannedtransaction.july, @plannedtransaction.july,  {checked:@plannedtransaction.july, disabled: true}) %></td>
  		<td><%= check_box(@plannedtransaction.august, @plannedtransaction.august,  {checked:@plannedtransaction.august, disabled: true}) %></td>
  		<td><%= check_box(@plannedtransaction.september, @plannedtransaction.september,  {checked:@plannedtransaction.september, disabled: true}) %></td>
  		<td><%= check_box(@plannedtransaction.october, @plannedtransaction.october,  {checked:@plannedtransaction.october, disabled: true}) %></td>
  		<td><%= check_box(@plannedtransaction.november, @plannedtransaction.november,  {checked:@plannedtransaction.november, disabled: true}) %></td>
  		<td><%= check_box(@plannedtransaction.december, @plannedtransaction.december,  {checked:@plannedtransaction.december, disabled: true}) %></td>
                 </tr>
    </tbody>
  </table>
</p>

<%= link_to 'Edit', edit_plannedtransaction_path(@plannedtransaction) %> |
<%= link_to 'Back', plannedtransactions_path %> |
<%= link_to 'Close and Clone', close_and_clone_plannedtransaction_path(@plannedtransaction), method: :patch %>