config/routes.rb
Rails.application.routes.draw do
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  scope '(:locale)' do
    resources :users
    resources :plannedtransactions do
      member do
        patch 'close_and_clone'
      end
      collection { post :buchungen_anzeigen }
    end
    resources :unique_planned_transactions
    resources :categories
    resources :transactions do
      collection { post :import }
      collection { delete :delete_all }
    end

    get '/gegenbuchung/', to: 'unique_planned_transactions#gegenbuchung', as: 'unique_planned_transactions_gegenbuchung'
    get '/transactions/:year/:month', to: 'transactions#show_by_year_month', as: 'transactions_show_by_year_month'

    get '/yearlybudget/:year/:month', to: 'budget_by_year#show_by_year', as: 'show_by_year', defaults: { percentage_or_absolute: 'percentage' }
    get '/yearlybudget', to: 'budget_by_year#index', as: 'budget_by_year_index'
    get '/yearlybudget_by_category/:year/:month/:category_id', to: 'budget_by_year#show_by_year_category', as: 'show_by_year_category', defaults: { percentage_or_absolute: 'percentage' }

    get '/budget/:year/:month', to: 'budget#show_by_year_month', as: 'show_by_year_month', defaults: { percentage_or_absolute: 'percentage' }
    get '/budget/:year/:month/percentage_or_absolute', to: 'budget#show_by_year_month', as: 'show_by_year_month_absolute', defaults: { percentage_or_absolute: 'absolute' }

    get '/budget_by_category/:year/:month/:category_id', to: 'budget#show_by_year_month_category', as: 'show_by_year_month_category'

    post '/buchungen_anzeigen', to: 'plannedtransactions#buchungen_anzeigen'
    
    root 'budget#index', as: 'budget_index'
  end
end

app/controllers/transactions_controller.rb
# frozen_string_literal: true

class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[show edit update destroy]
  before_action :set_user, only: %i[index import delete_all create show_by_year_month]

  # GET /transactions
  # GET /transactions.json
  def index
    @year = Date.today.year.to_s
    @month = Date.today.month.to_s
    show_by_year_month
  end

  def show_by_year_month
    Integer @month = params[:month] unless params[:month].nil?
    Integer @year = params[:year] unless params[:year].nil?
    @first_day_of_the_month_to_show = Date.new(Integer(@year), Integer(@month), 0o1)
    @transactions = @user.transactions.between(@first_day_of_the_month_to_show.at_beginning_of_month, @first_day_of_the_month_to_show.at_end_of_month).order(moneymoney_id: :desc)
    @transactions_without_category = @user.transactions.where(category_id: nil)
    render :index
  end

  def import
    account_name = Transaction.account_name(params[:file].path, @user)
    @user.transactions.where(booked: false, account_name: account_name).destroy_all
    Transaction.import(params[:file].path, @user)
    redirect_to transactions_url, notice: 'Transactions imported!'
  end

  def delete_all
    @user.transactions.destroy_all
    redirect_to transactions_url, notice: 'Transactions deleted!'
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show; end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit; end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.user = @user

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_user
    @user = User.find(session[:user_id])
  end

  def set_transaction
    @transaction = Transaction.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def transaction_params
    params.require(:transaction).permit(:moneymoney_id, :occurance_date, :category_id, :name, :purpose, :account, :bank, :amount, :file, :booked, :month, :year)
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper

  def get_path_for_show_by_year_month_next_month(current_date)
    next_month = current_date.beginning_of_month.next_month
    transactions_show_by_year_month_path(next_month.year, next_month.month)
  end

  def get_path_for_show_by_year_month_previous_month(current_date)
    previous_month = current_date.beginning_of_month.prev_month
    transactions_show_by_year_month_path(previous_month.year, previous_month.month)
  end
end

app/views/transactions/_form.html.erb
<%= form_for(transaction) do |f| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :moneymoney_id %>
    <%= f.number_field :moneymoney_id %>
  </div>

  <div class="field">
    <%= f.label :account_name %>
    <%= f.text_field :account_name, disabled: 'disabled' %>
  </div>

  <div class="field">
    <%= f.label :booked %>
    <%= f.check_box :booked %>
  </div>

  <div class="field">
    <%= f.label :occurance_date %>
    <%= f.date_select :occurance_date %>
  </div>

  <div class="field">
    <%= f.label :category_id %>
     <%= f.select :category_id, Category.where(user_id: session[:user_id]).order(:name).collect {|p| [ p.name, p.id ]}, {include_blank: 'None'} %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :purpose %>
    <%= f.text_field :purpose %>
  </div>

  <div class="field">
    <%= f.label :account %>
    <%= f.text_field :account %>
  </div>

  <div class="field">
    <%= f.label :bank %>
    <%= f.text_field :bank %>
  </div>

  <div class="field">
    <%= f.label :amount %>
    <%= f.text_field :amount %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transactions/_transaction.html.erb
<tr>
					<td style="text-align: left;" title ="<%= transaction.purpose %>" >
						<%= link_to transaction.name, edit_transaction_path(transaction) %>
					</td>
					<td><%= number_to_currency(transaction.amount) %></td>
					</tr>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<p id="notice"><%= notice %></p>

<%= form_tag import_transactions_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import CSV" %>
<% end %>



<h1>Transactions without category</h1>
<table>
  <thead>
    <tr>
      <th>Moneymoney</th>
      <th>Account Name</>
      <th>Occurance date</th>
      <th>Category</th>
      <th>Name</th>
      <th>Purpose</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
      <% @transactions_without_category.each do |transaction| %>
        <tr <%= "class=not-booked" unless transaction.booked %> >
          <td><%= transaction.moneymoney_id %></td>
          <td><%= transaction.account_name %></td>
          <td><%= transaction.occurance_date %></td>
          <td><%= Category.find(transaction.category_id).name unless transaction.category_id.nil?%></td>
          <td><%= transaction.name %></td>
          <td><%= transaction.purpose %></td>
          <td><%= transaction.amount %></td>
          <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
          <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
  </tbody>
</table>

<h1 style="text-align:center;">
	<%= link_to '<', get_path_for_show_by_year_month_previous_month(@first_day_of_the_month_to_show) %><%= t('transactions') %> <%= t('for') %> <%= l(@first_day_of_the_month_to_show, format: "%B") %> <%= @year %>  <%= link_to '>', get_path_for_show_by_year_month_next_month(@first_day_of_the_month_to_show) %>
</h1>
<table>
  <thead>
    <tr>
      <th>Moneymoney</th>
      <th>Account Name</>
      <th>Occurance date</th>
      <th>Category</th>
      <th>Name</th>
      <th>Purpose</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @transactions.each do |transaction| %>
      <tr <%= "class=not-booked" unless transaction.booked? %>>
        <td><%= transaction.moneymoney_id %></td>
        <td><%= transaction.account_name %></td>
        <td><%= transaction.occurance_date %></td>
        <td><%= Category.find(transaction.category_id).name unless transaction.category_id.nil?%></td>
        <td><%= transaction.name %></td>
        <td><%= transaction.purpose %></td>
        <td><%= transaction.amount %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Transaction', new_transaction_path %>
<%= link_to 'Delete all Transactions', delete_all_transactions_path, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>MoneMoney_id:</strong>
  <%= @transaction.moneymoney_id %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>